apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
namePrefix: user-project-
resources:
- basic-deployment.yaml
images:
- name: base-image
  newName: notemann27/backstage-test
  newTag: "latest"

