name: Deploy repository in cluster

on:
  workflow_dispatch:
    inputs:
      projectUrl:
        description: URL of the project to be hosted
        required: true


jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      run: |
        echo "${{ github.event.inputs.projectUrl }}"
        git clone ${{ github.event.inputs.projectUrl }} ~/user-project
        cd ~/user-project
        git log --oneline

